### ISSUE TITLE
FatalError: Timed out waiting for packet content ESP8266-ESP-01s AND Arduino UNO 

### ISSUE THREAD

**Issue by warshockII** [ubidots/ubidots-esp8266#40]
helppp

i tried to use your examples. SendValueTCP.ino

and change the value of wifi information ssid and pwd

but the only problem is by uploading it gives me...

esptool.py v2.8
Serial port COM6
Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.3/tools/upload.py", line 65, in <module>
    esptool.main(cmdline)
  File "C:/Users/username/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.3/tools/esptool\esptool.py", line 2890, in main
    esp.connect(args.before)
  File "C:/Users/username/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.6.3/tools/esptool\esptool.py", line 483, in connect
    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header
esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

_

**Comment by jotathebest** [comment]
From the debug message, your issue is related with your hardware or physical connection due:

`esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header`

Closing as this is not related with the Ubidots library but with the Espressif firmware utility.
